import { z } from "zod";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Config, ImageProvider } from "../types.js";
import { generateHtmlPage, escapeHtml, escapeJsString, safeJsonForScript } from "./templates.js";
import { createImageProvider } from "./image-generator.js";

export const AddBookingInput = {
  siteDir: z.string().describe("Absolute path to existing site directory"),
  services: z.array(z.string()).describe("List of bookable services (e.g. ['Haircut', 'Massage'])"),
  businessName: z.string().optional().describe("Business name for the booking page header"),
};

type AddBookingInputType = {
  siteDir: string;
  services: string[];
  businessName?: string;
};

export interface AddBookingResult {
  files: string[];
  siteDir: string;
  imagesGenerated: number;
}

export async function addBooking(
  input: AddBookingInputType,
  opts: { imageProvider: ImageProvider & { name: string } }
): Promise<AddBookingResult> {
  const { siteDir, services, businessName = "Book an Appointment" } = input;
  const { imageProvider } = opts;

  const files: string[] = [];
  mkdirSync(join(siteDir, "images"), { recursive: true });
  mkdirSync(join(siteDir, "workers", "booking-api"), { recursive: true });

  // Generate hero image for booking page
  const heroPrompt = `Modern appointment booking for ${businessName}`;
  await imageProvider.generate(heroPrompt, join(siteDir, "images", "booking-hero.png"));
  files.push("images/booking-hero.png");

  // --- book.css ---
  const bookCss = `/* book.css — generated by web-builder-mcp */

.booking-hero {
  background: var(--color-bg-alt);
  border-bottom: 1px solid var(--color-border);
  padding: var(--spacing-2xl) var(--spacing-md);
  text-align: center;
  position: relative;
  overflow: hidden;
}
.booking-hero-bg {
  position: absolute;
  inset: 0;
  background-size: cover;
  background-position: center;
  opacity: 0.18;
  z-index: 0;
}
.booking-hero > .container {
  position: relative;
  z-index: 1;
}
.booking-hero h1 { font-size: 2rem; font-weight: 800; }
.booking-hero p { color: var(--color-text-muted); margin-top: var(--spacing-sm); }

/* Progress steps */
.steps-indicator {
  display: flex;
  justify-content: center;
  gap: 0;
  margin-bottom: var(--spacing-2xl);
  padding: 0;
  list-style: none;
}
.step-item {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--color-text-muted);
}
.step-item::after {
  content: '';
  display: block;
  width: 2rem;
  height: 2px;
  background: var(--color-border);
  margin: 0 var(--spacing-sm);
}
.step-item:last-child::after { display: none; }
.step-item.active { color: var(--color-primary); }
.step-item.done { color: var(--color-primary); opacity: 0.7; }
.step-num {
  width: 1.75rem;
  height: 1.75rem;
  border-radius: 50%;
  background: var(--color-border);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.8rem;
  font-weight: 700;
}
.step-item.active .step-num { background: var(--color-primary); color: #fff; }
.step-item.done .step-num { background: var(--color-primary); color: #fff; }

/* Booking form */
.booking-section { padding: var(--spacing-3xl) 0; }
.booking-card {
  max-width: 640px;
  margin-inline: auto;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--spacing-2xl);
  box-shadow: var(--shadow-sm);
}
.booking-step { display: none; }
.booking-step.active { display: block; }
.booking-step h2 { font-size: 1.25rem; font-weight: 700; margin-bottom: var(--spacing-xl); }

/* Service selection */
.service-list { display: flex; flex-direction: column; gap: var(--spacing-sm); }
.service-option {
  display: flex;
  align-items: center;
  gap: var(--spacing-md);
  padding: var(--spacing-md) var(--spacing-lg);
  border: 2px solid var(--color-border);
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: border-color var(--transition), background var(--transition);
}
.service-option:hover { border-color: var(--color-primary); background: var(--color-bg-alt); }
.service-option.selected { border-color: var(--color-primary); background: rgba(37,99,235,0.05); }
.service-option input[type="radio"] { accent-color: var(--color-primary); }
.service-label { font-weight: 600; }

/* Date/time picker */
.date-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--spacing-sm);
  margin-bottom: var(--spacing-xl);
}
.time-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--spacing-sm);
}
.date-btn, .time-btn {
  padding: var(--spacing-sm) var(--spacing-md);
  border: 2px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-surface);
  cursor: pointer;
  font-size: 0.875rem;
  font-weight: 600;
  text-align: center;
  transition: border-color var(--transition), background var(--transition);
}
.date-btn:hover, .time-btn:hover { border-color: var(--color-primary); }
.date-btn.selected, .time-btn.selected { border-color: var(--color-primary); background: var(--color-primary); color: #fff; }

/* Confirmation */
.confirm-summary {
  background: var(--color-bg-alt);
  border-radius: var(--radius-md);
  padding: var(--spacing-lg);
  margin-bottom: var(--spacing-xl);
}
.confirm-summary p { margin-bottom: var(--spacing-sm); }
.confirm-summary strong { color: var(--color-primary); }

/* Step nav */
.step-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: var(--spacing-xl);
  padding-top: var(--spacing-lg);
  border-top: 1px solid var(--color-border);
}
.booking-success {
  text-align: center;
  padding: var(--spacing-3xl) var(--spacing-md);
  display: none;
}
.booking-success.active { display: block; }
.booking-error { text-align: center; margin-bottom: var(--spacing-lg); }
.success-icon { font-size: 4rem; margin-bottom: var(--spacing-lg); }

@media (min-width: 768px) {
  .date-grid { grid-template-columns: repeat(4, 1fr); }
  .time-grid { grid-template-columns: repeat(4, 1fr); }
}
`;
  writeFileSync(join(siteDir, "book.css"), bookCss, "utf-8");
  files.push("book.css");

  // --- book.js ---
  const serviceOptions = services.map((s) => `'${escapeJsString(s)}'`).join(", ");

  const bookJs = `/* book.js — generated by web-builder-mcp */
(function () {
  'use strict';

  const SERVICES = [${serviceOptions}];
  let currentStep = 1;
  let booking = { service: null, date: null, time: null, name: '', email: '', phone: '' };

  function showError(msg) {
    var el = document.getElementById('booking-error');
    if (el) { el.textContent = msg; el.style.display = 'block'; }
  }

  function clearError() {
    var el = document.getElementById('booking-error');
    if (el) { el.textContent = ''; el.style.display = 'none'; }
  }

  function showStep(step) {
    clearError();
    document.querySelectorAll('.booking-step').forEach(function (el) {
      el.classList.remove('active');
    });
    document.querySelectorAll('.step-item').forEach(function (el, i) {
      el.classList.remove('active', 'done');
      if (i + 1 < step) el.classList.add('done');
      if (i + 1 === step) el.classList.add('active');
    });
    const stepEl = document.getElementById('step-' + step);
    if (stepEl) stepEl.classList.add('active');
    currentStep = step;
  }

  function next() {
    if (currentStep === 1 && !booking.service) {
      showError('Please select a service.');
      return;
    }
    if (currentStep === 2 && (!booking.date || !booking.time)) {
      showError('Please select a date and time.');
      return;
    }
    if (currentStep === 3) {
      const nameEl = document.getElementById('book-name');
      const emailEl = document.getElementById('book-email');
      if (!nameEl || !nameEl.value.trim() || !emailEl || !emailEl.value.trim()) {
        showError('Please fill in your name and email.');
        return;
      }
      booking.name = nameEl.value.trim();
      booking.email = emailEl.value.trim();
      const phoneEl = document.getElementById('book-phone');
      if (phoneEl) booking.phone = phoneEl.value.trim();
      updateSummary();
    }
    showStep(currentStep + 1);
  }

  function back() {
    if (currentStep > 1) showStep(currentStep - 1);
  }

  function updateSummary() {
    const s = document.getElementById('summary-service');
    const d = document.getElementById('summary-date');
    const t = document.getElementById('summary-time');
    const n = document.getElementById('summary-name');
    const e = document.getElementById('summary-email');
    if (s) s.textContent = booking.service || '-';
    if (d) d.textContent = booking.date || '-';
    if (t) t.textContent = booking.time || '-';
    if (n) n.textContent = booking.name || '-';
    if (e) e.textContent = booking.email || '-';
  }

  async function submitBooking() {
    const btn = document.getElementById('confirm-btn');
    if (btn) btn.disabled = true;
    try {
      await fetch('/workers/booking-api/notify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(booking),
      });
    } catch (err) {
      console.error('Booking submit error:', err);
    }
    // Show success regardless (graceful degradation)
    document.getElementById('booking-form-area').style.display = 'none';
    const success = document.getElementById('booking-success');
    if (success) success.classList.add('active');
  }

  document.addEventListener('DOMContentLoaded', function () {
    // Render services
    const serviceList = document.getElementById('service-list');
    if (serviceList) {
      serviceList.innerHTML = SERVICES.map(function (svc) {
        return '<label class="service-option"><input type="radio" name="service" value="' + svc + '"> <span class="service-label">' + svc + '</span></label>';
      }).join('');
      serviceList.querySelectorAll('input[type="radio"]').forEach(function (radio) {
        radio.addEventListener('change', function () {
          booking.service = this.value;
          serviceList.querySelectorAll('.service-option').forEach(function (el) { el.classList.remove('selected'); });
          this.closest('.service-option').classList.add('selected');
        });
      });
    }

    // Render date options (next 7 days)
    const dateGrid = document.getElementById('date-grid');
    if (dateGrid) {
      const days = [];
      for (let i = 1; i <= 7; i++) {
        const d = new Date();
        d.setDate(d.getDate() + i);
        if (d.getDay() !== 0) { // skip Sundays
          days.push({ label: d.toLocaleDateString('en', { weekday: 'short', month: 'short', day: 'numeric' }), value: d.toISOString().split('T')[0] });
        }
      }
      dateGrid.innerHTML = days.map(function (d) {
        return '<button type="button" class="date-btn" data-value="' + d.value + '">' + d.label + '</button>';
      }).join('');
      dateGrid.querySelectorAll('.date-btn').forEach(function (btn) {
        btn.addEventListener('click', function () {
          booking.date = this.dataset.value;
          dateGrid.querySelectorAll('.date-btn').forEach(function (b) { b.classList.remove('selected'); });
          this.classList.add('selected');
        });
      });
    }

    // Render time slots
    const timeGrid = document.getElementById('time-grid');
    if (timeGrid) {
      const times = ['9:00 AM','10:00 AM','11:00 AM','1:00 PM','2:00 PM','3:00 PM','4:00 PM'];
      timeGrid.innerHTML = times.map(function (t) {
        return '<button type="button" class="time-btn" data-value="' + t + '">' + t + '</button>';
      }).join('');
      timeGrid.querySelectorAll('.time-btn').forEach(function (btn) {
        btn.addEventListener('click', function () {
          booking.time = this.dataset.value;
          timeGrid.querySelectorAll('.time-btn').forEach(function (b) { b.classList.remove('selected'); });
          this.classList.add('selected');
        });
      });
    }

    // Step navigation
    document.querySelectorAll('[data-next]').forEach(function (btn) { btn.addEventListener('click', next); });
    document.querySelectorAll('[data-back]').forEach(function (btn) { btn.addEventListener('click', back); });

    const confirmBtn = document.getElementById('confirm-btn');
    if (confirmBtn) confirmBtn.addEventListener('click', submitBooking);

    showStep(1);
  });
})();
`;
  writeFileSync(join(siteDir, "book.js"), bookJs, "utf-8");
  files.push("book.js");

  // --- book.html ---
  const serviceOptionHtml = services
    .map(
      (s) => `
                <label class="service-option">
                  <input type="radio" name="service" value="${escapeHtml(s)}">
                  <span class="service-label">${escapeHtml(s)}</span>
                </label>`
    )
    .join("\n");

  // Detect existing nav links and business name from index.html
  let bookNavLinks: Array<{ href: string; label: string }> | undefined;
  let bookBusinessName: string | undefined;
  let bookLang: string | undefined;
  const bookIndexPath = join(siteDir, "index.html");
  if (existsSync(bookIndexPath)) {
    try {
      const indexContent = readFileSync(bookIndexPath, "utf-8");
      const logoMatch = indexContent.match(/class="nav-logo">([^<]+)</);
      if (logoMatch) bookBusinessName = logoMatch[1];
      const langMatch = indexContent.match(/<html[^>]+lang="([^"]+)"/);
      if (langMatch) bookLang = langMatch[1];
      const linkMatches = [...indexContent.matchAll(/class="nav-links"[\s\S]*?<\/ul>/g)];
      if (linkMatches.length > 0) {
        const navHtml = linkMatches[0][0];
        const hrefMatches = [...navHtml.matchAll(/<a href="([^"]+)">([^<]+)<\/a>/g)];
        if (hrefMatches.length > 0) {
          bookNavLinks = hrefMatches.map((m) => ({ href: m[1], label: m[2] }));
        }
      }
    } catch {
      // Ignore read errors
    }
  }

  const bookingLdJson = JSON.stringify(
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: `Book an Appointment — ${bookBusinessName ?? businessName}`,
      description: `Book an appointment online with ${bookBusinessName ?? businessName}`,
    },
    null,
    2
  );

  const safeBookingName = escapeHtml(bookBusinessName ?? businessName);
  const bookBodyContent = `    <div class="booking-hero">
      <div class="booking-hero-bg" aria-hidden="true"></div>
      <div class="container">
        <h1>Book an Appointment</h1>
        <p>${safeBookingName} — online booking in minutes.</p>
      </div>
    </div>

    <section class="booking-section">
      <div class="container">

        <!-- Progress indicator -->
        <ol class="steps-indicator" aria-label="Booking progress">
          <li class="step-item active"><span class="step-num">1</span> Service</li>
          <li class="step-item"><span class="step-num">2</span> Date &amp; Time</li>
          <li class="step-item"><span class="step-num">3</span> Your details</li>
          <li class="step-item"><span class="step-num">4</span> Confirm</li>
        </ol>

        <div id="booking-form-area">
          <div id="booking-error" class="form-error booking-error" role="alert"></div>
          <div class="booking-card">

            <!-- Step 1: Choose service -->
            <div id="step-1" class="booking-step active">
              <h2>Select a service</h2>
              <div id="service-list" class="service-list">
${serviceOptionHtml}
              </div>
              <div class="step-nav">
                <span></span>
                <button type="button" class="btn btn-primary" data-next>Next &rarr;</button>
              </div>
            </div>

            <!-- Step 2: Date and time -->
            <div id="step-2" class="booking-step">
              <h2>Choose a date</h2>
              <div id="date-grid" class="date-grid"></div>
              <h2 class="mt-xl">Choose a time</h2>
              <div id="time-grid" class="time-grid"></div>
              <div class="step-nav">
                <button type="button" class="btn btn-outline" data-back>&larr; Back</button>
                <button type="button" class="btn btn-primary" data-next>Next &rarr;</button>
              </div>
            </div>

            <!-- Step 3: Details -->
            <div id="step-3" class="booking-step">
              <h2>Your details</h2>
              <p class="required-note"><span class="required-star">*</span> Required fields</p>
              <div class="form-group">
                <label for="book-name">Full name <span class="required-star">*</span></label>
                <input type="text" id="book-name" name="name" required autocomplete="name" placeholder="Your name">
              </div>
              <div class="form-group">
                <label for="book-email">Email address <span class="required-star">*</span></label>
                <input type="email" id="book-email" name="email" required autocomplete="email" placeholder="you@example.com">
              </div>
              <div class="form-group">
                <label for="book-phone">Phone number</label>
                <input type="tel" id="book-phone" name="phone" autocomplete="tel" placeholder="Optional">
              </div>
              <div class="step-nav">
                <button type="button" class="btn btn-outline" data-back>&larr; Back</button>
                <button type="button" class="btn btn-primary" data-next>Review booking &rarr;</button>
              </div>
            </div>

            <!-- Step 4: Confirm -->
            <div id="step-4" class="booking-step">
              <h2>Confirm your booking</h2>
              <div class="confirm-summary">
                <p><strong>Service:</strong> <span id="summary-service"></span></p>
                <p><strong>Date:</strong> <span id="summary-date"></span></p>
                <p><strong>Time:</strong> <span id="summary-time"></span></p>
                <p><strong>Name:</strong> <span id="summary-name"></span></p>
                <p><strong>Email:</strong> <span id="summary-email"></span></p>
              </div>
              <div class="step-nav">
                <button type="button" class="btn btn-outline" data-back>&larr; Back</button>
                <button type="button" id="confirm-btn" class="btn btn-primary">Confirm booking</button>
              </div>
            </div>

          </div><!-- .booking-card -->
        </div><!-- #booking-form-area -->

        <!-- Success state -->
        <div id="booking-success" class="booking-success">
          <div class="success-icon">✅</div>
          <h2>Booking confirmed!</h2>
          <p>We'll send a confirmation to your email shortly.</p>
          <a href="index.html" class="btn btn-primary mt-xl">Back to home</a>
        </div>

      </div>
    </section>

    <script type="application/ld+json">
${safeJsonForScript(bookingLdJson)}
    </script>`;

  const bookHtml = generateHtmlPage({
    title: `Book — ${bookBusinessName ?? businessName}`,
    bodyContent: bookBodyContent,
    lang: bookLang,
    description: `Book an appointment online with ${bookBusinessName ?? businessName}`,
    businessName: bookBusinessName ?? businessName,
    navLinks: bookNavLinks,
    extraCss: ["book.css"],
    extraJs: ["book.js"],
    canonicalUrl: "book.html",
    extraHead: `  <style>.booking-hero-bg { background-image: url('images/booking-hero.png'); }</style>`,
  });
  writeFileSync(join(siteDir, "book.html"), bookHtml, "utf-8");
  files.push("book.html");

  // --- workers/booking-api/index.js ---
  const workerJs = `/* workers/booking-api/index.js — generated by web-builder-mcp */
/* Deploy with: wrangler deploy */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
  });
}

function corsResponse() {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') return corsResponse();

    if (url.pathname === '/health') {
      return json({ status: 'ok', timestamp: new Date().toISOString() });
    }

    if (url.pathname === '/notify' && request.method === 'POST') {
      try {
        const body = await request.json();
        const { service, date, time, name, email, phone } = body;

        if (!service || !date || !time || !name || !email) {
          return json({ error: 'Missing required fields' }, 400);
        }

        // TODO: Send email notification via env.RESEND_API_KEY or env.SENDGRID_API_KEY
        // Example:
        // await fetch('https://api.resend.com/emails', {
        //   method: 'POST',
        //   headers: { Authorization: \`Bearer \${env.RESEND_API_KEY}\`, 'Content-Type': 'application/json' },
        //   body: JSON.stringify({
        //     from: 'bookings@yourdomain.com',
        //     to: env.NOTIFY_EMAIL,
        //     subject: \`New booking: \${service} on \${date}\`,
        //     html: \`<p>Name: \${name}</p><p>Email: \${email}</p><p>Service: \${service}</p><p>Date: \${date} at \${time}</p>\`,
        //   }),
        // });

        return json({ ok: true, message: 'Booking received. Configure RESEND_API_KEY to enable email notifications.' });
      } catch (err) {
        return json({ error: 'Invalid request body' }, 400);
      }
    }

    return new Response('Not found', { status: 404 });
  },
};
`;
  writeFileSync(join(siteDir, "workers", "booking-api", "index.js"), workerJs, "utf-8");
  files.push("workers/booking-api/index.js");

  // --- workers/booking-api/wrangler.toml ---
  const wranglerToml = `name = "booking-api"
main = "index.js"
compatibility_date = "2024-01-01"

# Add your secrets:
# wrangler secret put RESEND_API_KEY
# wrangler secret put NOTIFY_EMAIL
`;
  writeFileSync(join(siteDir, "workers", "booking-api", "wrangler.toml"), wranglerToml, "utf-8");
  files.push("workers/booking-api/wrangler.toml");

  return { files, siteDir, imagesGenerated: 1 };
}

export function registerAddBooking(server: McpServer, config: Config): void {
  const provider = createImageProvider(config);
  server.registerTool(
    "add_booking",
    {
      description:
        "Add a multi-step booking system to an existing site: service selection, date/time picker, details form, AI-generated hero image, and a Cloudflare Worker for notifications",
      inputSchema: AddBookingInput,
    },
    async (args) => {
      const result = await addBooking(args as AddBookingInputType, { imageProvider: provider });
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );
}
