import { z } from "zod";
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Config, ImageProvider } from "../types.js";
import { generateHtmlPage, escapeHtml, safeJsonForScript } from "./templates.js";
import { createImageProvider } from "./image-generator.js";

export const AddShopInput = {
  siteDir: z.string().describe("Absolute path to existing site directory"),
  products: z
    .array(
      z.object({
        name: z.string(),
        price: z.number().describe("Price in dollars"),
        description: z.string().optional(),
        tags: z.array(z.string()).optional(),
      })
    )
    .describe("Products to add to the shop"),
  currency: z.string().optional().default("USD").describe("Currency code (e.g. USD, AUD)"),
};

type Product = {
  name: string;
  price: number;
  description?: string;
  tags?: string[];
};

type AddShopInputType = {
  siteDir: string;
  products: Product[];
  currency?: string;
};

export interface AddShopResult {
  files: string[];
  siteDir: string;
  imagesGenerated: number;
  imageProvider: string;
  estimatedImageCost: string;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export async function addShop(
  input: AddShopInputType,
  opts: { imageProvider: ImageProvider & { name: string } }
): Promise<AddShopResult> {
  const { siteDir, products, currency = "USD" } = input;
  const { imageProvider } = opts;

  const files: string[] = [];

  // Ensure images dir and workers dir
  mkdirSync(join(siteDir, "images"), { recursive: true });
  mkdirSync(join(siteDir, "workers", "shop-api"), { recursive: true });

  // Generate product images
  const productsWithIds = await Promise.all(
    products.map(async (p, i) => {
      const slug = slugify(p.name);
      const imgPath = join(siteDir, "images", `product-${slug}.png`);
      const prompt = `Professional product photo of ${p.name}${p.description ? ` — ${p.description}` : ""}. Clean white background, studio lighting, commercial product photography`;
      await imageProvider.generate(prompt, imgPath);
      files.push(`images/product-${slug}.png`);
      return {
        id: `prod-${slug}-${i + 1}`,
        slug,
        ...p,
      };
    })
  );

  // --- products.json ---
  writeFileSync(join(siteDir, "products.json"), JSON.stringify(productsWithIds, null, 2), "utf-8");
  files.push("products.json");

  // --- shop.css ---
  const shopCss = `/* shop.css — generated by web-builder-mcp */

.shop-hero {
  background: var(--color-bg-alt);
  border-bottom: 1px solid var(--color-border);
  padding: var(--spacing-2xl) var(--spacing-md);
  text-align: center;
}
.shop-hero h1 { font-size: 2rem; font-weight: 800; }
.shop-hero p { color: var(--color-text-muted); margin-top: var(--spacing-sm); }

/* Product grid */
.product-grid {
  display: grid;
  gap: var(--spacing-lg);
  grid-template-columns: 1fr;
  padding: var(--spacing-2xl) 0;
}
.product-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow-sm);
  transition: box-shadow var(--transition), transform var(--transition);
  display: flex;
  flex-direction: column;
}
.product-card:hover {
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}
.product-img {
  aspect-ratio: 1;
  background: var(--color-bg-alt);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}
.product-img img { width: 100%; height: 100%; object-fit: cover; }
.product-info { padding: var(--spacing-lg); flex: 1; display: flex; flex-direction: column; gap: var(--spacing-sm); }
.product-name { font-weight: 700; font-size: 1.05rem; }
.product-desc { color: var(--color-text-muted); font-size: 0.9rem; flex: 1; }
.product-price { font-weight: 700; color: var(--color-primary); font-size: 1.25rem; }
.product-tags { display: flex; flex-wrap: wrap; gap: var(--spacing-xs); }
.product-tag {
  font-size: 0.75rem;
  padding: 2px 8px;
  background: var(--color-bg-alt);
  border: 1px solid var(--color-border);
  border-radius: 999px;
  color: var(--color-text-muted);
}
.btn-add-cart {
  width: 100%;
  margin-top: var(--spacing-md);
  background: var(--color-primary);
  color: #fff;
  border: none;
  padding: 0.625rem 1rem;
  border-radius: var(--radius-md);
  font-weight: 600;
  cursor: pointer;
  font-size: 1rem;
  transition: background var(--transition);
}
.btn-add-cart:hover { background: var(--color-primary-dark, #1e40af); }

/* Cart drawer */
.cart-btn {
  position: fixed;
  bottom: var(--spacing-xl);
  right: var(--spacing-xl);
  background: var(--color-primary);
  color: #fff;
  border: none;
  border-radius: 999px;
  padding: 0.75rem 1.25rem;
  font-weight: 700;
  font-size: 1rem;
  cursor: pointer;
  box-shadow: var(--shadow-lg);
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  z-index: 200;
  transition: background var(--transition);
}
.cart-btn:hover { background: var(--color-primary-dark, #1e40af); }
.cart-count {
  background: #fff;
  color: var(--color-primary);
  border-radius: 999px;
  width: 1.5rem;
  height: 1.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.8rem;
  font-weight: 700;
}

.cart-drawer {
  position: fixed;
  top: 0;
  right: -480px;
  width: min(480px, 100vw);
  height: 100%;
  background: var(--color-surface);
  box-shadow: var(--shadow-lg);
  z-index: 300;
  display: flex;
  flex-direction: column;
  transition: right 0.3s ease;
}
.cart-drawer.is-open { right: 0; }
.cart-drawer-header {
  padding: var(--spacing-lg);
  border-bottom: 1px solid var(--color-border);
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.cart-drawer-header h2 { font-size: 1.25rem; font-weight: 700; }
.cart-close {
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
  padding: var(--spacing-xs);
  border-radius: var(--radius-md);
  color: var(--color-text-muted);
}
.cart-items { flex: 1; overflow-y: auto; padding: var(--spacing-md); }
.cart-empty { text-align: center; color: var(--color-text-muted); padding: var(--spacing-2xl); }
.cart-item {
  display: flex;
  gap: var(--spacing-md);
  padding: var(--spacing-md) 0;
  border-bottom: 1px solid var(--color-border);
}
.cart-item-name { font-weight: 600; flex: 1; }
.cart-item-price { color: var(--color-primary); font-weight: 600; white-space: nowrap; }
.cart-item-qty { display: flex; align-items: center; gap: var(--spacing-sm); }
.qty-btn {
  background: var(--color-bg-alt);
  border: 1px solid var(--color-border);
  width: 1.75rem;
  height: 1.75rem;
  border-radius: var(--radius-sm);
  cursor: pointer;
  font-weight: 700;
  font-size: 1rem;
}
.cart-footer {
  padding: var(--spacing-lg);
  border-top: 1px solid var(--color-border);
}
.cart-total { font-size: 1.125rem; font-weight: 700; margin-bottom: var(--spacing-md); display: flex; justify-content: space-between; }
.btn-checkout {
  width: 100%;
  background: var(--color-primary);
  color: #fff;
  border: none;
  padding: 0.875rem 1rem;
  border-radius: var(--radius-md);
  font-size: 1.125rem;
  font-weight: 700;
  cursor: pointer;
  transition: background var(--transition);
}
.btn-checkout:hover { background: var(--color-primary-dark, #1e40af); }

.cart-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.4);
  z-index: 299;
  display: none;
}
.cart-remove {
  background: none;
  border: none;
  cursor: pointer;
  color: #dc2626;
  font-size: 1.25rem;
  padding: var(--spacing-xs);
  border-radius: var(--radius-sm);
  line-height: 1;
}
.cart-remove:hover { color: #b91c1c; }

.cart-overlay.is-open { display: block; }

@media (min-width: 768px) {
  .product-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (min-width: 1280px) {
  .product-grid { grid-template-columns: repeat(3, 1fr); }
}
`;
  writeFileSync(join(siteDir, "shop.css"), shopCss, "utf-8");
  files.push("shop.css");

  // --- shop.js ---
  const shopJs = `/* shop.js — generated by web-builder-mcp */
(function () {
  'use strict';

  const CURRENCY = '${currency}';
  let products = [];
  let cart = [];

  function loadCart() {
    try { cart = JSON.parse(localStorage.getItem('cart') || '[]'); } catch { cart = []; }
  }

  function saveCart() {
    localStorage.setItem('cart', JSON.stringify(cart));
  }

  function formatPrice(cents) {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: CURRENCY }).format(cents / 100);
  }

  function addToCart(productId) {
    const product = products.find(p => p.id === productId);
    if (!product) return;
    const existing = cart.find(i => i.id === productId);
    if (existing) { existing.qty += 1; } else { cart.push({ id: productId, name: product.name, price: product.price, qty: 1 }); }
    saveCart();
    renderCart();
    openCart();
  }

  function removeFromCart(productId) {
    cart = cart.filter(i => i.id !== productId);
    saveCart();
    renderCart();
  }

  function changeQty(productId, delta) {
    const item = cart.find(i => i.id === productId);
    if (!item) return;
    item.qty += delta;
    if (item.qty <= 0) { removeFromCart(productId); return; }
    saveCart();
    renderCart();
  }

  function openCart() {
    document.querySelector('.cart-drawer').classList.add('is-open');
    document.querySelector('.cart-overlay').classList.add('is-open');
  }

  function closeCart() {
    document.querySelector('.cart-drawer').classList.remove('is-open');
    document.querySelector('.cart-overlay').classList.remove('is-open');
  }

  function renderCart() {
    const itemsEl = document.getElementById('cart-items');
    const totalEl = document.getElementById('cart-total');
    const countEl = document.getElementById('cart-count');
    const totalCount = cart.reduce((sum, i) => sum + i.qty, 0);
    const totalCents = cart.reduce((sum, i) => sum + i.price * 100 * i.qty, 0);
    if (countEl) countEl.textContent = totalCount.toString();
    if (totalEl) totalEl.textContent = formatPrice(totalCents);
    if (!itemsEl) return;
    if (cart.length === 0) {
      itemsEl.innerHTML = '<p class="cart-empty">Your cart is empty.</p>';
      return;
    }
    itemsEl.innerHTML = cart.map(item => \`
      <div class="cart-item">
        <div class="cart-item-name">\${item.name}</div>
        <div class="cart-item-qty">
          <button class="qty-btn" onclick="changeCartQty('\${item.id}', -1)" aria-label="Decrease">-</button>
          <span>\${item.qty}</span>
          <button class="qty-btn" onclick="changeCartQty('\${item.id}', 1)" aria-label="Increase">+</button>
        </div>
        <div class="cart-item-price">\${formatPrice(item.price * 100 * item.qty)}</div>
        <button class="cart-remove" onclick="removeCartItem('\${item.id}')" aria-label="Remove">&times;</button>
      </div>
    \`).join('');
  }

  async function checkout() {
    if (cart.length === 0) return;
    const btn = document.getElementById('checkout-btn');
    if (btn) btn.disabled = true;
    try {
      const res = await fetch('/workers/shop-api/create-checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ items: cart.map(i => ({ id: i.id, name: i.name, price: i.price, qty: i.qty })) }),
      });
      const data = await res.json();
      if (data.url) { window.location.href = data.url; }
    } catch (err) {
      console.error('Checkout error:', err);
      if (btn) btn.disabled = false;
    }
  }

  // Expose globals for inline handlers
  window.changeCartQty = changeQty;
  window.removeCartItem = removeFromCart;

  document.addEventListener('DOMContentLoaded', async function () {
    loadCart();

    // Load products
    try {
      const res = await fetch('products.json');
      products = await res.json();
    } catch { products = []; }

    // Render product grid
    const grid = document.getElementById('product-grid');
    if (grid && products.length > 0) {
      grid.innerHTML = products.map(p => \`
        <div class="product-card">
          <div class="product-img"><img src="images/product-\${p.slug || p.id}.png" alt="\${p.name}" loading="lazy"></div>
          <div class="product-info">
            <div class="product-name">\${p.name}</div>
            \${p.description ? \`<div class="product-desc">\${p.description}</div>\` : ''}
            \${p.tags && p.tags.length ? \`<div class="product-tags">\${p.tags.map(t => \`<span class="product-tag">\${t}</span>\`).join('')}</div>\` : ''}
            <div class="product-price">\${formatPrice(p.price * 100)}</div>
            <button class="btn-add-cart" onclick="addToCart('\${p.id}')">Add to cart</button>
          </div>
        </div>
      \`).join('');
    }

    window.addToCart = addToCart;

    // Cart toggle
    const cartBtn = document.getElementById('cart-btn');
    if (cartBtn) cartBtn.addEventListener('click', openCart);

    const cartClose = document.getElementById('cart-close');
    if (cartClose) cartClose.addEventListener('click', closeCart);

    const cartOverlay = document.querySelector('.cart-overlay');
    if (cartOverlay) cartOverlay.addEventListener('click', closeCart);

    const checkoutBtn = document.getElementById('checkout-btn');
    if (checkoutBtn) checkoutBtn.addEventListener('click', checkout);

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') closeCart();
    });

    renderCart();
  });
})();
`;
  writeFileSync(join(siteDir, "shop.js"), shopJs, "utf-8");
  files.push("shop.js");

  // --- shop.html ---
  const productCards = productsWithIds
    .map(
      (p) => `
      <div class="product-card">
        <div class="product-img"><img src="images/product-${escapeHtml(p.slug)}.png" alt="${escapeHtml(p.name)}" loading="lazy"></div>
        <div class="product-info">
          <div class="product-name">${escapeHtml(p.name)}</div>
          ${p.description ? `<div class="product-desc">${escapeHtml(p.description)}</div>` : ""}
          <div class="product-price">${p.price.toFixed(2)} ${escapeHtml(currency)}</div>
          <button class="btn-add-cart" onclick="addToCart('${escapeHtml(p.id)}')">Add to cart</button>
        </div>
      </div>`
    )
    .join("\n");

  // LD+JSON with Product items
  const shopLdJson = JSON.stringify(
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      name: "Shop",
      itemListElement: productsWithIds.map((p, i) => ({
        "@type": "ListItem",
        position: i + 1,
        item: {
          "@type": "Product",
          name: p.name,
          description: p.description ?? "",
          image: `images/product-${p.slug}.png`,
          offers: {
            "@type": "Offer",
            price: p.price.toFixed(2),
            priceCurrency: currency,
            availability: "https://schema.org/InStock",
          },
        },
      })),
    },
    null,
    2
  );

  // Detect existing nav links from index.html if present
  let shopNavLinks: Array<{ href: string; label: string }> | undefined;
  let shopBusinessName: string | undefined;
  let shopLang: string | undefined;
  const indexPath = join(siteDir, "index.html");
  if (existsSync(indexPath)) {
    try {
      const indexContent = readFileSync(indexPath, "utf-8");
      const logoMatch = indexContent.match(/class="nav-logo">([^<]+)</);
      if (logoMatch) shopBusinessName = logoMatch[1];
      const langMatch = indexContent.match(/<html[^>]+lang="([^"]+)"/);
      if (langMatch) shopLang = langMatch[1];
      // Extract nav links from existing page
      const linkMatches = [...indexContent.matchAll(/class="nav-links"[\s\S]*?<\/ul>/g)];
      if (linkMatches.length > 0) {
        const navHtml = linkMatches[0][0];
        const hrefMatches = [...navHtml.matchAll(/<a href="([^"]+)">([^<]+)<\/a>/g)];
        if (hrefMatches.length > 0) {
          shopNavLinks = hrefMatches.map((m) => ({ href: m[1], label: m[2] }));
        }
      }
    } catch {
      // Ignore read errors
    }
  }

  // Ensure shop is in nav links
  if (shopNavLinks && !shopNavLinks.some((l) => l.href === "shop.html")) {
    shopNavLinks.push({ href: "shop.html", label: "Shop" });
  }

  const shopBodyContent = `    <div class="shop-hero">
      <div class="container">
        <h1>Our Shop</h1>
        <p>Browse our full range of products.</p>
      </div>
    </div>

    <div class="container">
      <div id="product-grid" class="product-grid">
${productCards}
      </div>
    </div>

    <!-- Cart drawer -->
    <aside class="cart-drawer" role="dialog" aria-labelledby="cart-heading" aria-modal="true">
      <div class="cart-drawer-header">
        <h2 id="cart-heading">Your cart</h2>
        <button id="cart-close" class="cart-close" aria-label="Close cart">&times;</button>
      </div>
      <div id="cart-items" class="cart-items">
        <p class="cart-empty">Your cart is empty.</p>
      </div>
      <div class="cart-footer">
        <div class="cart-total"><span>Total</span><span id="cart-total">$0.00</span></div>
        <button id="checkout-btn" class="btn-checkout">Checkout</button>
      </div>
    </aside>

    <!-- Floating cart button -->
    <button id="cart-btn" class="cart-btn" aria-label="Open cart">
      Cart <span id="cart-count" class="cart-count">0</span>
    </button>

    <div class="cart-overlay" aria-hidden="true"></div>

    <script type="application/ld+json">
${safeJsonForScript(shopLdJson)}
    </script>`;

  const shopHtml = generateHtmlPage({
    title: `Shop — ${shopBusinessName ?? "Shop"}`,
    bodyContent: shopBodyContent,
    lang: shopLang,
    description: "Shop our products",
    businessName: shopBusinessName,
    navLinks: shopNavLinks,
    extraCss: ["shop.css"],
    extraJs: ["shop.js"],
    canonicalUrl: "shop.html",
  });
  writeFileSync(join(siteDir, "shop.html"), shopHtml, "utf-8");
  files.push("shop.html");

  // --- workers/shop-api/index.js ---
  const workerJs = `/* workers/shop-api/index.js — generated by web-builder-mcp */
/* Deploy with: wrangler deploy */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
  });
}

function corsResponse() {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === 'OPTIONS') return corsResponse();

    if (url.pathname === '/health') {
      return json({ status: 'ok', timestamp: new Date().toISOString() });
    }

    if (url.pathname === '/create-checkout' && request.method === 'POST') {
      try {
        const body = await request.json();
        const { items } = body;

        if (!items || !Array.isArray(items) || items.length === 0) {
          return json({ error: 'No items in cart' }, 400);
        }

        // Calculate total in cents
        const totalCents = items.reduce((sum, item) => {
          const price = Math.round(item.price * 100);
          const qty = parseInt(item.qty, 10) || 1;
          return sum + price * qty;
        }, 0);

        // TODO: Integrate with Stripe or preferred payment provider
        // Example: const session = await stripe.checkout.sessions.create({ ... });
        // return json({ url: session.url });

        // Placeholder response
        return json({
          ok: true,
          totalCents,
          message: 'Checkout integration not yet configured. Set STRIPE_SECRET_KEY in wrangler.toml secrets.',
        });
      } catch (err) {
        return json({ error: 'Invalid request body' }, 400);
      }
    }

    if (url.pathname === '/webhook' && request.method === 'POST') {
      // TODO: Verify webhook signature and process payment events
      return json({ received: true });
    }

    return new Response('Not found', { status: 404 });
  },
};
`;
  writeFileSync(join(siteDir, "workers", "shop-api", "index.js"), workerJs, "utf-8");
  files.push("workers/shop-api/index.js");

  // --- workers/shop-api/wrangler.toml ---
  const wranglerToml = `name = "shop-api"
main = "index.js"
compatibility_date = "2024-01-01"

# Add your secrets:
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put STRIPE_WEBHOOK_SECRET
`;
  writeFileSync(join(siteDir, "workers", "shop-api", "wrangler.toml"), wranglerToml, "utf-8");
  files.push("workers/shop-api/wrangler.toml");

  return {
    files,
    siteDir,
    imagesGenerated: products.length,
    imageProvider: imageProvider.name,
    estimatedImageCost: imageProvider.name === "gemini-2.5-flash"
      ? `~$${(products.length * 0.04).toFixed(3)}`
      : "$0.00",
  };
}

export function registerAddShop(server: McpServer, config: Config): void {
  const provider = createImageProvider(config);
  server.registerTool(
    "add_shop",
    {
      description:
        "Add e-commerce functionality to an existing site: product grid with AI-generated product images, cart drawer, shop.js with localStorage, and a Cloudflare Worker for checkout",
      inputSchema: AddShopInput,
    },
    async (args) => {
      const result = await addShop(args as AddShopInputType, { imageProvider: provider });
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(result, null, 2),
          },
        ],
      };
    }
  );
}
