/**
 * Shared HTML/CSS/JS template fragments for all build tools.
 * Pure utility module — no MCP registration.
 */

/**
 * Escape a string for safe insertion into HTML content or attributes.
 * Prevents XSS from user-supplied business names, product names, etc.
 */
export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * Escape a string for safe insertion into a JavaScript string literal
 * (single-quoted). Handles backslashes, quotes, newlines, and
 * HTML script-closing sequences.
 */
export function escapeJsString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/<\//g, "<\\/");
}

/**
 * Make a JSON string safe for embedding inside an HTML <script> tag.
 * Prevents `</script>` sequences in JSON values from closing the script block.
 */
export function safeJsonForScript(json: string): string {
  return json.replace(/<\//g, "<\\/");
}

export interface StylesOpts {
  primaryColor?: string;
  secondaryColor?: string;
  fontFamily?: string;
  accentColor?: string;
}

export interface HtmlPageOpts {
  title: string;
  bodyContent: string;
  lang?: string;
  description?: string;
  primaryColor?: string;
  fontFamily?: string;
  extraHead?: string;
  navLinks?: Array<{ href: string; label: string }>;
  businessName?: string;
  cssFile?: string;
  jsFile?: string;
  extraCss?: string[];
  extraJs?: string[];
  canonicalUrl?: string;
}

export function generateStyles(opts: StylesOpts): string {
  const primary = opts.primaryColor ?? "#2563eb";
  const secondary = opts.secondaryColor ?? "#1e40af";
  const accent = opts.accentColor ?? "#f59e0b";
  const font = opts.fontFamily ?? "Inter, system-ui, sans-serif";

  return `/* Generated by web-builder-mcp */

:root {
  --color-primary: ${primary};
  --color-primary-dark: ${secondary};
  --color-secondary: ${secondary};
  --color-accent: ${accent};
  --color-bg: #ffffff;
  --color-bg-alt: #f8fafc;
  --color-text: #1e293b;
  --color-text-muted: #64748b;
  --color-border: #e2e8f0;
  --color-surface: #ffffff;
  --font-family: ${font};
  --font-size-base: 1rem;
  --line-height-base: 1.6;
  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 1.5rem;
  --spacing-xl: 2rem;
  --spacing-2xl: 3rem;
  --spacing-3xl: 4rem;
  --radius-sm: 0.25rem;
  --radius-md: 0.5rem;
  --radius-lg: 1rem;
  --shadow-sm: 0 1px 2px rgba(0,0,0,0.05);
  --shadow-md: 0 4px 6px rgba(0,0,0,0.07);
  --shadow-lg: 0 10px 15px rgba(0,0,0,0.1);
  --max-width: 1200px;
  --nav-height: 64px;
  --transition: 200ms ease;
}

/* Reset */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: var(--font-family);
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
  color: var(--color-text);
  background: var(--color-bg);
}
img, video { max-width: 100%; height: auto; display: block; }
a { color: var(--color-primary); text-decoration: none; }
a:hover { text-decoration: underline; }

/* Skip link */
.skip-link {
  position: absolute;
  top: -100%;
  left: var(--spacing-md);
  background: var(--color-primary);
  color: #fff;
  padding: var(--spacing-sm) var(--spacing-md);
  border-radius: 0 0 var(--radius-md) var(--radius-md);
  font-weight: 600;
  z-index: 9999;
  transition: top var(--transition);
}
.skip-link:focus { top: 0; }

/* Focus visible */
:focus-visible {
  outline: 3px solid var(--color-primary);
  outline-offset: 2px;
  border-radius: var(--radius-sm);
}

/* Layout utilities */
.container { width: 100%; max-width: var(--max-width); margin-inline: auto; padding-inline: var(--spacing-md); }
.container-narrow { max-width: 720px; margin-inline: auto; }
.container-form { max-width: 600px; margin-inline: auto; }
.mt-xl { margin-top: var(--spacing-xl); }
.form-error { color: #dc2626; margin-bottom: var(--spacing-md); display: none; }
.form-success { color: #16a34a; margin-bottom: var(--spacing-md); display: none; }
.visually-hidden { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; }
.text-center { text-align: center; }
.flow > * + * { margin-top: var(--spacing-md); }

/* Navigation */
.site-header {
  position: sticky;
  top: 0;
  z-index: 100;
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  box-shadow: var(--shadow-sm);
}
.nav-inner {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: var(--nav-height);
}
.nav-logo {
  font-size: 1.25rem;
  font-weight: 700;
  color: var(--color-primary);
}
.nav-logo:hover { text-decoration: none; }
.nav-toggle {
  display: flex;
  flex-direction: column;
  gap: 5px;
  background: none;
  border: none;
  cursor: pointer;
  padding: var(--spacing-sm);
  border-radius: var(--radius-md);
}
.nav-toggle span {
  display: block;
  width: 24px;
  height: 2px;
  background: var(--color-text);
  border-radius: 2px;
  transition: transform var(--transition), opacity var(--transition);
}
.nav-toggle[aria-expanded="true"] span:nth-child(1) { transform: translateY(7px) rotate(45deg); }
.nav-toggle[aria-expanded="true"] span:nth-child(2) { opacity: 0; }
.nav-toggle[aria-expanded="true"] span:nth-child(3) { transform: translateY(-7px) rotate(-45deg); }
.nav-links {
  display: none;
  list-style: none;
  flex-direction: column;
  position: absolute;
  top: var(--nav-height);
  left: 0;
  right: 0;
  background: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
  padding: var(--spacing-md);
  gap: var(--spacing-sm);
}
.nav-links.is-open { display: flex; }
.nav-links a {
  display: block;
  padding: var(--spacing-sm) var(--spacing-md);
  border-radius: var(--radius-md);
  color: var(--color-text);
  font-weight: 500;
}
.nav-links a:hover { background: var(--color-bg-alt); text-decoration: none; }
.nav-overlay {
  display: none;
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.4);
  z-index: 99;
}
.nav-overlay.is-open { display: block; }

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: 0.625rem 1.25rem;
  border-radius: var(--radius-md);
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  border: 2px solid transparent;
  transition: background var(--transition), color var(--transition), border-color var(--transition);
  text-decoration: none;
}
.btn-primary {
  background: var(--color-primary);
  color: #fff;
}
.btn-primary:hover { background: var(--color-primary-dark); text-decoration: none; }
.btn-outline {
  background: transparent;
  color: var(--color-primary);
  border-color: var(--color-primary);
}
.btn-outline:hover { background: var(--color-primary); color: #fff; text-decoration: none; }

/* Hero */
.hero {
  background: linear-gradient(135deg, var(--color-primary) 0%, var(--color-primary-dark) 100%);
  color: #fff;
  text-align: center;
  padding: var(--spacing-3xl) var(--spacing-md);
}
.hero h1 { font-size: 2rem; font-weight: 800; line-height: 1.2; margin-bottom: var(--spacing-lg); }
.hero p { font-size: 1.125rem; max-width: 600px; margin-inline: auto; margin-bottom: var(--spacing-xl); opacity: 0.9; }
.hero-cta { display: flex; gap: var(--spacing-md); justify-content: center; flex-wrap: wrap; }
.btn-hero-secondary { background: #fff; color: var(--color-primary); }

/* Sections */
.section { padding: var(--spacing-3xl) 0; }
.section-alt { background: var(--color-bg-alt); }
.section-title { font-size: 1.75rem; font-weight: 700; margin-bottom: var(--spacing-md); }
.section-lead { color: var(--color-text-muted); max-width: 640px; margin-inline: auto; margin-bottom: var(--spacing-2xl); }

/* Feature grid */
.feature-grid {
  display: grid;
  gap: var(--spacing-lg);
  grid-template-columns: 1fr;
}
.feature-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  padding: var(--spacing-xl);
  box-shadow: var(--shadow-sm);
}
.feature-icon { font-size: 2rem; margin-bottom: var(--spacing-md); }
.feature-card h3 { font-size: 1.125rem; font-weight: 700; margin-bottom: var(--spacing-sm); }
.feature-card p { color: var(--color-text-muted); }

/* CTA */
.cta { background: var(--color-primary); color: #fff; text-align: center; padding: var(--spacing-3xl) var(--spacing-md); }
.cta h2 { font-size: 1.75rem; font-weight: 700; margin-bottom: var(--spacing-md); }
.cta p { opacity: 0.9; max-width: 560px; margin-inline: auto; margin-bottom: var(--spacing-xl); }
.cta .btn-outline { border-color: #fff; color: #fff; }
.cta .btn-outline:hover { background: #fff; color: var(--color-primary); }

/* Footer */
.site-footer {
  background: #1e293b;
  color: #94a3b8;
  text-align: center;
  padding: var(--spacing-xl) var(--spacing-md);
  font-size: 0.875rem;
}
.site-footer a { color: #94a3b8; }
.site-footer a:hover { color: #fff; }

/* Forms */
.form-group { margin-bottom: var(--spacing-lg); }
.form-group label {
  display: block;
  font-weight: 600;
  margin-bottom: var(--spacing-xs);
  color: var(--color-text);
}
.form-group input,
.form-group select,
.form-group textarea {
  width: 100%;
  padding: 0.625rem var(--spacing-md);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  font-family: var(--font-family);
  font-size: 1rem;
  color: var(--color-text);
  background: var(--color-surface);
  transition: border-color var(--transition);
}
.form-group input:focus,
.form-group select:focus,
.form-group textarea:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 3px rgba(37,99,235,0.15);
}
.required-note { font-size: 0.875rem; color: var(--color-text-muted); margin-bottom: var(--spacing-lg); }
.required-star { color: #dc2626; }

/* Page header */
.page-header {
  background: var(--color-bg-alt);
  border-bottom: 1px solid var(--color-border);
  padding: var(--spacing-2xl) var(--spacing-md);
  text-align: center;
}
.page-header h1 { font-size: 2rem; font-weight: 800; }
.page-header p { color: var(--color-text-muted); margin-top: var(--spacing-sm); }

@media (min-width: 768px) {
  .container { padding-inline: var(--spacing-xl); }
  .nav-toggle { display: none; }
  .nav-links {
    display: flex;
    flex-direction: row;
    position: static;
    border-bottom: none;
    padding: 0;
    background: transparent;
  }
  .nav-links a { padding: var(--spacing-xs) var(--spacing-md); }
  .hero h1 { font-size: 2.75rem; }
  .feature-grid { grid-template-columns: repeat(2, 1fr); }
  .section-title { font-size: 2rem; }
}

@media (min-width: 1280px) {
  .hero h1 { font-size: 3.5rem; }
  .feature-grid { grid-template-columns: repeat(3, 1fr); }
  .section-title { font-size: 2.25rem; }
}
`;
}

export function generateSiteJs(): string {
  return `/* Generated by web-builder-mcp — site.js */
(function () {
  'use strict';

  // Mobile nav toggle
  const navToggle = document.querySelector('.nav-toggle');
  const navLinks = document.querySelector('.nav-links');
  const navOverlay = document.querySelector('.nav-overlay');

  function openNav() {
    if (!navToggle || !navLinks) return;
    navLinks.classList.add('is-open');
    navToggle.setAttribute('aria-expanded', 'true');
    if (navOverlay) navOverlay.classList.add('is-open');
    document.body.style.overflow = 'hidden';
  }

  function closeNav() {
    if (!navToggle || !navLinks) return;
    navLinks.classList.remove('is-open');
    navToggle.setAttribute('aria-expanded', 'false');
    if (navOverlay) navOverlay.classList.remove('is-open');
    document.body.style.overflow = '';
  }

  if (navToggle) {
    navToggle.addEventListener('click', function () {
      const isOpen = navToggle.getAttribute('aria-expanded') === 'true';
      if (isOpen) { closeNav(); } else { openNav(); }
    });
  }

  // Overlay click-to-close
  if (navOverlay) {
    navOverlay.addEventListener('click', closeNav);
  }

  // Escape key handler for all overlays
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') {
      closeNav();
      // Close any other open overlays
      document.querySelectorAll('.overlay.is-open, .drawer.is-open').forEach(function (el) {
        el.classList.remove('is-open');
      });
    }
  });

  // Dynamic copyright year
  const yearEls = document.querySelectorAll('.copyright-year');
  yearEls.forEach(function (el) {
    el.textContent = new Date().getFullYear().toString();
  });

})();
`;
}

export function generateHtmlPage(opts: HtmlPageOpts): string {
  const lang = opts.lang ?? "en-US";
  const description = escapeHtml(opts.description ?? "");
  const safeTitle = escapeHtml(opts.title);
  const businessName = opts.businessName ?? safeTitle;
  const cssFile = opts.cssFile ?? "styles.css";
  const jsFile = opts.jsFile ?? "site.js";
  const extraCss = opts.extraCss ?? [];
  const extraJs = opts.extraJs ?? [];

  const defaultNavLinks = [
    { href: "index.html", label: "Home" },
    { href: "about.html", label: "About" },
    { href: "contact.html", label: "Contact" },
  ];
  const navLinks = opts.navLinks ?? defaultNavLinks;

  const navItems = navLinks.map((l) => `        <li><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></li>`).join("\n");
  const extraCssTags = extraCss.map((f) => `  <link rel="stylesheet" href="${f}">`).join("\n");
  const extraJsTags = extraJs.map((f) => `  <script src="${f}" defer></script>`).join("\n");

  const canonicalTag = opts.canonicalUrl
    ? `  <link rel="canonical" href="${opts.canonicalUrl}">\n`
    : "";

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${description}">
  <meta property="og:title" content="${safeTitle}">
  <meta property="og:description" content="${description}">
  <meta property="og:type" content="website">
  <title>${safeTitle}</title>
${canonicalTag}  <link rel="stylesheet" href="${cssFile}">
${extraCssTags ? extraCssTags + "\n" : ""}${opts.extraHead ?? ""}
</head>
<body>
  <a href="#main" class="skip-link">Skip to content</a>

  <div class="nav-overlay" aria-hidden="true"></div>

  <header class="site-header">
    <div class="container nav-inner">
      <a href="index.html" class="nav-logo">${businessName}</a>
      <button class="nav-toggle" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <nav aria-label="Main navigation">
        <ul class="nav-links">
${navItems}
        </ul>
      </nav>
    </div>
  </header>

  <main id="main">
${opts.bodyContent}
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>&copy; <span class="copyright-year"></span> ${businessName}. All rights reserved.</p>
    </div>
  </footer>

  <script src="${jsFile}" defer></script>
${extraJsTags ? extraJsTags + "\n" : ""}</body>
</html>`;
}
